name: Lambda Status Page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lambda
      run: |
        cd packages/lambda
        npm ci
        npm run build --if-present
        npm run lint
        npm run test:coverage
        cd ../..
    - name: Frontend
      run: |
        cd packages/frontend
        npm ci
        npm run build --if-present
        npm run lint
        cd ../..
      env:
        CI: true
