name: Lambda Status Page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lambda
      with:
        cwd: packages/lambda
      run: npm ci
      run: npm run lint
      run: npm run test:coverage
    - name: Frontend
      with:
        cwd: packages/frontend
      run: npm ci
      run: npm run lint
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
